all: counting-inversions-brute-force counting-inversions-divide-conquer

counting-inversions-brute-force: counting-inversions-brute-force.c
	gcc -Wall counting-inversions-brute-force.c -o counting-inversions-brute-force

counting-inversions-divide-conquer: counting-inversions-divide-conquer.c
	gcc -Wall counting-inversions-divide-conquer.c -o counting-inversions-divide-conquer

clean:
	rm -rf *.o counting-inversions-brute-force counting-inversions-divide-conquer
